### ISSUE TITLE
This doesn't work with koa2

### ISSUE THREAD

**Issue by wbsimms** [SimonDegraeve/koa-browser-sync#3]

**Comment by aendrew** [comment]
Out of the box, no, but it's possible to use koa-convert:

First, install `node-http-proxy` separately as the version used by `koa-browser-sync` is outdated and crashes (see #4):

```
npm install http-proxy --save-dev
npm install koa-browser-sync --save-dev
npm install koa@next koa-convert --save # If you haven't installed them yet
```

Then:

```
import convert from 'koa-convert';
import koaBS from 'koa-browser-sync';
import Koa from 'koa';

const app = new Koa();
if (app.env === 'development') {
  app.use(convert(koaBS({ init: true })));
}
app.listen(3000);
```

**Comment by aendrew** [comment]
@SimonDegraeve I've updated this lib to use promises as per Koa 2 — are you interested in maintaining it (in which case I'll PR my code as a new branch named `next`), or should I fork it to a new repo?

**Comment by SimonDegraeve** [comment]
The module is now updated to run with the latest versions of Koa and BrowserSync.
